### ISSUE TITLE
Openscoring war deployment on Tomcat- admin role authorization

### ISSUE THREAD

**Issue by cong78** [openscoring/openscoring#37]
Hi, 

I am deploying the Openscoring WAR on tomcat to access remotely. But when I started it and tried to PUT request with my PMML model it tells me a message of 403 user not authorized. I saw the documentation that you can configure the trusted IP through application.conf when running the Openscoring JAR. 
So my question is how can I do the same thing with Openscoring WAR on tomcat? By changing the web.xml in WEB-INF?

Thanks,

Cong

**Comment by JokeCiCi** [comment]
The reason is that NetworkSecurityContextFilter this class do intercept, you can modify the configuration file openscoring\openscoring-service\src\main\resources\reference.conf, will you want to PUT, DELETE node host configuration in, like trustedAddresses = ["192.168.0.1"], and repackaged to deploy

**Comment by vruusmann** [comment]
Openscoring is a standard Java web application. You can configure user roles, including the "admin" role, at Tomcat web container level.

To avoid confusion, you might want to remove/comment out the `NetworkSecurityContextFilter` directive in your configuration file afterwards.
