### ISSUE TITLE
[Question] Default folder for loading models?

### ISSUE THREAD

**Issue by tribeclickgh** [openscoring/openscoring#39]
I was wondering, is there any way that we can set up models when the service starts?

**Comment by vruusmann** [comment]
Openscoring is completely stateless by design. It doesn't need and doesn't want to care about its surrounding deployment environment. 

For a stateful startup, you should create your own launch script that 1) starts the Openscoring REST web service, 2) scans a "model archive directory" for model files (eg. using ".pmml" file extension filter) and 3) uploads all those model files via Openscoring model upload REST API endpoint.

I can imagine that the above workflow could be implemented as a ten-line shell script.
