### ISSUE TITLE
Secured requests

### ISSUE THREAD

**Issue by elsayedrashed** [openscoring/openscoring#57]
Any way to make all deployment and scoring requests are secured (using token).

Any example code available?

**Comment by vruusmann** [comment]
There are two layers of security:

1. Physical layer - activating the HTTPS protocol, so that the transmitted data is safe from eavesdropping.
2. Logical layer - checking that end users are allowed to perform the requested action. Openscoring distinguishes between admin (read-write; reading private content) and non-admin user actions (read only; public content).

A token allows you to address the logical layer security. It is assumed that you have already solved the physical layer security independently (eg. HTTPS ensures that other people can't see your tokens).

The default logical security is IP address-based - some addresses are trusted, all the others are not:
https://github.com/openscoring/openscoring/tree/2.1.1/openscoring-service/src/main/resources/reference.conf#L12-L14

If you want to activate tokens, then you need to replace this config item with "org.openscoring.service.filters.TokenSecurityContextFilter":
```
application {
	componentClasses = [
		"org.openscoring.service.filters.TokenSecurityContextFilter"
	]
}
```

The implementation is here:
https://github.com/openscoring/openscoring/blob/2.1.1/openscoring-service/src/main/java/org/openscoring/service/filters/TokenSecurityContextFilter.java

When you restart the system so that the new config can take effect, you shall have a new token-based security in effect:
https://github.com/openscoring/openscoring/blob/2.1.1/openscoring-service/src/main/resources/reference.conf#L52-L61

The value of the admin token is re-generated on each service start - it's printed into the log file. You may want to replace it with your own constant value.
